### ISSUE TITLE
从图像中检测物体的原始代码可以提供吗

### ISSUE THREAD

**Issue by xwaiyy123** [sx-zhang/HOZ#3]
你好，我看了你了工作之后感觉有研究价值，你能提供用fasterrcnn从图像中检测物体的原始代码吗？

**Comment by sx-zhang** [comment]
你好，检测部分的结果我们是follow[ORG](https://github.com/xiaobaishu0097/ECCV-VN)这个工作的结果，其中检测的部分源码作者并没有公开，如果你需要从模拟器中保存检测结果的代码可以关注我们这个工程[tools](https://github.com/sx-zhang/some-tools-of-navigation)这里会将如何离散化模拟器，并保存相应的结果的代码开源。但如果你想继续研究objec navigation这个任务，并复现结果的话，我建议你还是沿用之前的检测结果，我们曾经尝试过从新采集检测结果，但这会导致很难复现ORG原论文的结果，此外，由于现在ai2thor模拟器版本进行比较大的更新，即使是有之前的检测代码，由于一些版本问题，或者初始化的问题（ai2thor的物体摆放位置是随机初始化）导致模拟器环境的差异，也很难复现出相关工作的结果。
