### ISSUE TITLE
这些scene graph的mat是怎么生成的?能提供代码么

### ISSUE THREAD

**Issue by Ubastic** [sx-zhang/HOZ#4]

**Comment by zwr-04** [comment]
作者您好！阅读了您的工作感觉很有启发，同样，希望您能提供生成四种场景的scene graph的mat文件的源代码，以供参考学习，谢谢！

**Comment by sx-zhang** [comment]
代码已更新，请参考[graph_generation](https://github.com/sx-zhang/HOZ/tree/main/graph_generation)
